### ISSUE TITLE
GitHub Sponsoring

### ISSUE THREAD

**Issue by martin-braun** [pschlan/cron-job.org#110]
@pschlan Thank you for this great piece of software.

I'm grateful for the software and the service itself. I'm also happy that this service is free, but I wish to donate through GitHub Sponsoring to give at least a little back. Can this be enabled?

**Comment by pschlan** [comment]
Thanks! I’m trying to enable this for my account. Currently stuck in the verification phase.

**Comment by martin-braun** [comment]
@pschlan No problem, please report and close this issue when it's ready. :)

**Comment by pschlan** [comment]
This should work now.
