### ISSUE TITLE
A successfully executed job that receives a 302 response is interpreted as "Failed (HTTP error)"

### ISSUE THREAD

**Issue by karentamrazyan** [pschlan/cron-job.org#111]
the cron job org site interprets a successfully executed job where a website return a 302 HTTP header as "Failed (HTTP error)"

**Comment by pschlan** [comment]
Usually a 302 status code requires a redirection to complete the job. Since we don’t follow redirects, we assume the execution didn’t finish completely. 

Why does your URL return a 302 in case of success?

**Comment by karentamrazyan** [comment]
This assumption is not very logical.

Here is a list of HTTP response categories:

- Informational responses (100–199)
- Successful responses (200–299)
- Redirection messages (300–399)
- Client error responses (400–499)
- Server error responses (500–599)

In my opinion you can only assume that something went wrong if a server returns 4XX or 5XX. Every other HTTP response is technically NOT a failure.

As per this particular case, the job in question successfully passes an authentication and then the server redirects the authenticated visitor to their dashboard. Again, the whole process is failure free, yet your service interprets it as a failure and disables the cron job after a few attempts.

Please, fix it or give us a way to define what is a failure.

**Comment by pschlan** [comment]
In most cases, jobs by our users get a 302 when the URL redirects to a https version or the www domain etc. Just treating the 3xx as successful would hide an actual problem in that case.

I'll check if I can make this configurable, though.

**Comment by karentamrazyan** [comment]
you could add a checkbox "treat a redirect response as a failed job", which can be on by default.

**Comment by pschlan** [comment]
This is now available in the "Advanced" tab of the job editor.
Thanks for reporting!

**Comment by karentamrazyan** [comment]
thanks! works like a charm!
