### ISSUE TITLE
Run every six days

### ISSUE THREAD

**Issue by foremtehan** [pschlan/cron-job.org#122]
Hey man thanks for the amazing service

I want to run specific cronjob every six days, i mean this expression

```
0 0 */6 * *
```

But coudn't find the way with the site UI, Is there any setting that gives me ability to edit expression directly ?

**Comment by rohit-chouhan** [comment]
agree

**Comment by pschlan** [comment]
You can use the custom schedule and, from the "Days of month" list, pick every 6th entry. For day of week and months, select everything, and for hour and minute, select only 0. That will emulate the behaviour of the expression you posted (`0 0 */6 * *`).
