### ISSUE TITLE
[Question] Is it possible to set the remote host IP?

### ISSUE THREAD

**Issue by ioweb-gr** [pschlan/cron-job.org#124]
Hi, 

I'm wondering if it's possible to bypass cloudflare checks for our servers by setting the remote host IP. Similar to 

` curl --insecure --resolve 'example.com:443:<ip>' -L '<url>'`

**Comment by pschlan** [comment]
To clarify: Do you want to connect directly to your backend host, bypassing the cloudflare proxy?

**Comment by ioweb-gr** [comment]
Yes exactly.

**Comment by pschlan** [comment]
This is not possible right now, but a nice feature suggestion. Let me check what I can do.

**Comment by pschlan** [comment]
@ioweb-gr Now that I think about this, you can try to set the URL to https://<ip>/... (e.g. replace the hostname by the IP address) and then add a custom header with key 'Host' and Value 'example.com' in the advanced section of the cron job. That should have the desired effect, if I'm not missing something.
