### ISSUE TITLE
Add time zone selection with auto detection to signup form

### ISSUE THREAD

**Issue by pschlan** [pschlan/cron-job.org#13]

**Comment by pschlan** [comment]
Done + deployed.

**Comment by cyntss** [comment]
Hi there! I was actually wondering how to set the time zone for my cronjob and found this closed issue.. but I can't find anywhere in cron-job.org a way to change that.

Can you please guide me?

**Comment by cyntss** [comment]
I found this in my account: 
![image](https://user-images.githubusercontent.com/5013096/49174273-2a6f5600-f346-11e8-8f61-94ddc8e3093c.png)

but the cron jobs don't seem to be paying attention to it
