### ISSUE TITLE
No account activation email sended

### ISSUE THREAD

**Issue by Kutikov** [pschlan/cron-job.org#130]
Please, help me to get activation email. I've registered on cron-job.com and waiting for activation email for 15 minutes. After that I request it one more time, but nothing happens. 
My browser: Chrome 100 on Android 11 OP8. Email on Gmail. Spam folder is empty too

**Comment by pschlan** [comment]
Can you please send your account email address to info@cron-job.org so I can check?

**Comment by Kutikov** [comment]
> Can you please send your account email address to [info@cron-job.org](mailto:info@cron-job.org) so I can check?

Sent.

**Comment by Kutikov** [comment]
Sent

вс, 24 апр. 2022 г., 13:09 Patrick Schlangen ***@***.***>:

**Comment by Kutikov** [comment]
No success

**Comment by pschlan** [comment]
Thanks. When did you sign up? I can't find any recent registration with that email address.

**Comment by pschlan** [comment]
Actually I found an account with a very similar email address. Sent you details via email.
