### ISSUE TITLE
How to schedule for every 15 minutes through API?

### ISSUE THREAD

**Issue by Sulivan1999** [pschlan/cron-job.org#134]
Hey! I'm trying to schedule a cron every 15 minutes via an API request. I checked the documentation but I couldn't understand how I can make this markup in this period of time.

**Comment by pschlan** [comment]
Try this: In the JobSchedule object, set `hours`, `mdays`, `months` and `wdays` to `[-1]` and `minutes` to `[0, 15, 30, 45]`.
