### ISSUE TITLE
Unable to change timeout

### ISSUE THREAD

**Issue by leifg** [pschlan/cron-job.org#137]
Hi there,

Love the service! It seems however that it is not possible to update the timeout setting. At least not to a higher setting than 30.

The site accepts the input without an error but after refresh it still shows 30.

**Comment by pschlan** [comment]
Hi,

the maximum timeout is 30 seconds for regular accounts. In case you entered a value above the maximum, the field should show marked in red.

I'll leave this report open to track UI enhancement to make this clearer.
