### ISSUE TITLE
Help wanted, 

### ISSUE THREAD

**Issue by Gupta-Anubhav12** [pschlan/cron-job.org#138]
Hii, I am not quite experienced in C++ and stuff and I was trying to build it locally to try some stuff, but I am facing issues with cctz linkers
![image](https://user-images.githubusercontent.com/64721638/170889150-9c8f905c-7576-4e4c-96fc-ccc2ec6d3c14.png)

**Comment by pschlan** [comment]
Looks like you're missing the cctz git submodule.
Try ```git submodule init
git submodule update``` in the repo root and then re-build.
