### ISSUE TITLE
How to set custom timeout for say 17 minutes

### ISSUE THREAD

**Issue by battaputha123** [pschlan/cron-job.org#149]
What is the correct way of setting the timeout for say a custom amount of minutes (say 17)

this means the crontab expression `*/17 * * * *`

i don't know how to achieve the `*/17` part from the UI by selecting minutes

**Comment by pschlan** [comment]
You can use a custom schedule like this:

- Minutes: 0, 17, 34, 51
- Hours: Select all
- Days of week: Select all
- Days of month: Select all
- Months: Select all

**Comment by battaputha123** [comment]
Thanks for the reply!
Yeah, this is somewhat what I tried.
The issue I was having was after 51 the next execution is at 0 which is 9 minutes apart.

**Comment by pschlan** [comment]
I believe this is also they way the cron daemon works when using */17, so the suggested custom schedule should still match the expression.
