### ISSUE TITLE
(solved) Include failure details in notification email

### ISSUE THREAD

**Issue by ecrode** [pschlan/cron-job.org#15]
Love your service and recommend it to everyone who needs a web based cron-job, but your failure notifications are unnecessarily vague. 
It would be great if response headers and body are included within cron-job failure notification.

The problem is that only the last 20 responses are available for examination and by the time I see a failure notification, it is too late to go back and check what went wrong.

Alternately, it would be nice to dedicate a certain number of responses to failures. For example instead of saving the last 20 responses, it would be possible to save the last 15 responses + 5 failures. A previously recorded failure should not be overridden by a successful response, but can be overridden by newer failure or your standard 2 day expiration. Ideally if no failures are present, normal responses are recorded instead.

I would be willing to help code the changes if they can be implemented within cron-job.org which is currently being used by many of my referrals.

Thank you,
Gene

**Comment by pschlan** [comment]
Hi Gene,

thanks a lot for your suggestion. I agree that this would totally make sense. Let me see what I can do as soon as I have some spare time.

Patrick

**Comment by ecrode** [comment]
I've already seen improvement! Thank you very much!
From emails:

Before:
        Last execution attempt: 01/01/1970 01:00:00 (geplant: 06/06/2017 11:25:00)
        Last status: Failed

After:
        Last execution attempt: 06/14/2017 04:30:07 (geplant: 06/14/2017 04:30:00)
        Last status: Failed (503 Service Unavailable: Back-end server is at capacity)

Thank you! 
Gene
