### ISSUE TITLE
[Feature Wish]: Trigger "URL" instead (or additional) of sending an e-mail 

### ISSUE THREAD

**Issue by xstable** [pschlan/cron-job.org#164]
Your service is really nice. Thanks for providing it.

As far as I see now, it's only possible to get a notification by email.

I would love to be able to set an external URL that would be triggered if an alert occur. 
This way it would be possible to integrate external services (like sending messages to Discord, Telegramm, etc.).

The script that does the magic (means sending those messages) may be lay on my webserver, but I need a way, that cron-job.org send an alert to this script to trigger it.

**Comment by a-tonchev** [comment]
That would be Amazing!

**Comment by pschlan** [comment]
Closed in favor of #215 - tracking further progress there.
