### ISSUE TITLE
Docker image in docker hub

### ISSUE THREAD

**Issue by manjeshpv** [pschlan/cron-job.org#166]
it would be helpful if dockerfile

**Comment by Sumis34** [comment]
Looking for the same thing. This would be awesome

**Comment by labs-mirkoisaia** [comment]
looking for the same thing

**Comment by uhlhosting** [comment]
Soon 1 year since, it seems there is not much interest to dockerize the app.

**Comment by morandalex** [comment]
dockerizing boost the adoption ... anyone working on it ?

**Comment by archraziel88** [comment]
i too have some experience with docker too, but couldn't manage to make it run, there are a lot of steos and dependencies taken for granted.

**Comment by pschlan** [comment]
I'm always available for specific questions, so feel free to ask :)

**Comment by ipanel** [comment]
Can a kind-hearted person make a mirror image for Docker

**Comment by pschlan** [comment]
Hi,

I have a rough prototype in the `docker` branch: https://github.com/pschlan/cron-job.org/tree/docker
Feel free to check it out and follow the instructions in README.md.
Would be curious if it works for you.
If positive, I will refine it a bit and merge it back to the main branch.

Best,

Patrick

**Comment by pschlan** [comment]
Merged to master, hence closing this issue.

**Comment by uhlhosting** [comment]
@pschlan it's nice you closed this, but this never solved the initial issue raised here. 

I asked you to public the images you build for docker, on docker hub, that would allow users to deploy the application, without the need to FORK the whole github project, and then run docker compose ... 


it would simply run docker compose based on the docker-compose.yml. and pull Mysql, redis, www, or what ever what images are needed from docker hub.
