### ISSUE TITLE
unable to delete job

### ISSUE THREAD

**Issue by honsberg** [pschlan/cron-job.org#176]
i cannot delete an job. because it says, i have a status monitor. but i dont have any.

![grafik](https://user-images.githubusercontent.com/12712721/213999423-413286a6-88bd-410b-a1f7-c34f0c40f02a.png)

![grafik](https://user-images.githubusercontent.com/12712721/213999583-0fe39984-d2fa-4a5c-aa04-6a0eeaa49f17.png)

https://console.cron-job.org/jobs/4067322

**Comment by pschlan** [comment]
Thanks for the report. Please try again, it should work now.
