### ISSUE TITLE
Is there any plan fot the Web Interface?

### ISSUE THREAD

**Issue by der-robert** [pschlan/cron-job.org#19]
Hi,

the deamon is now running on my Server. But i don't now insert Crons in my MySQL Table (whitch format). Exist any Tutorial?

**Comment by pschlan** [comment]
Hi,

yes, there is. We just didn't have time yet to get it ready for publishing.

I'm trying to explain briefly how to insert manually / with your own scripts:

First, create a user in the _user_ table.

The, for every job, insert a new row into the _job_ table
- jobid: Auto-increment, will be assigned by MySQL
- userid: ID of the user (references the _user_ table)
- title: An arbitrary title for the job
- url: The URL to fetch
- auth_enable: Set to '1' if job requires HTTP auth
- auth_user, auth_pass: Login info (if auth_enable is '1')
- notify_failure, notify_success, notify_disable: Notification settings, you can leave this as '0' for now
- last_status, last_fetch, last_duration, fail_counter: Just leave at the default value '0', will be populated by chronos
- save_responses: Whether to save the responses of the job or not
- request_method: Request method to use, see _RequestMethod_ enum in _chronos/HTTPRequest.h_ (0 = GET)

Then, insert the job schedule into the _job\_hours_, _job\_mdays_, _job\minutes_, _job\_months_, _job\_wdays_ tables. As the jobid column use the ID of the job you've created in the _job_ table. The ranges of the values are:
- hours: 0..23
- mdays: 1..31
- minutes: 0..59
- months: 1..12
- wdays: 0 (Sunday), 1 (Monday) .. 6 (Staturday)

The job will be executed whenever the current time can be found in the (hours, mdays, minutes, months, wdays) entries of the job. Example: If you want the job to execute every day at 10:30 and 12:30, insert the following:
- hours: Insert values 10, 12
- mdays: Insert values 1 .. 31 (i.e. don't care which day of month it is)
- minutes: Insert value 30
- months: Insert values 1 .. 12 (i.e. don't care which month it is)
- wdays: Insert values 0 .. 6 (i.e. don't care which day of week it is)

**Note:** This requires quite a lot of rows in the scheduling tables for many types of jobs. It's optimized on easy and fast scheduling implementation in the chronos daemon. The tables are small and lookup should be fast.

**Comment by gnanet** [comment]
I would suggest, until you get to publish the WebUI source, place a link to this issue into the README

**Comment by pschlan** [comment]
Frontend code is published by now
