### ISSUE TITLE
Receive time too long

### ISSUE THREAD

**Issue by arpitdalal** [pschlan/cron-job.org#192]
Why does receive time look like this? My other jobs have receive time of 0ms but this is 28s?
What am I doing wrong?
The endpoint scrapes through a site and gives back a response depending upon what it finds and I've checked manually that the endpoint doesn't take 30s to give response.

![image](https://user-images.githubusercontent.com/61059807/224144888-fe4f3ebe-5f0a-487a-8225-d60f122b711d.png)

**Comment by arpitdalal** [comment]
Test run also suceeds, just the job itself fails for some reason 🤷‍♂️
![image](https://user-images.githubusercontent.com/61059807/224148052-b4f44298-c12b-4834-b0d8-2a5dd1f4b236.png)

**Comment by pschlan** [comment]
This means we're actually waiting for ~ 30 seconds until your endpoint signals that the request has been completed. It doesn't matter when the first response from the endpoint comes, but how long it takes for the complete request to be completed (e.g. your server closing the connection).

I can send you a more verbose log from our side if you could send me the exact endpoint or cron job ID to info@cron-job.org, referencing this issue (#192). Thanks.
