### ISSUE TITLE
Cloudflare bot protection blocks cron-job.org

### ISSUE THREAD

**Issue by johnm1998** [pschlan/cron-job.org#203]
Currently the bot protection of cloudflare is blocking cron-job.org. Please add the website to cloudflare verified bot list here. https://radar.cloudflare.com/traffic/verified-bots

**Comment by pschlan** [comment]
We did, and they keep on ignoring us.

**Comment by pschlan** [comment]
I've submitted once again. If that's also being ignored, I don't know what else to do.

**Comment by pschlan** [comment]
Closing this as this is not an issue we can resolve. This would rather be an issue for CloudFlare. We tried multiple times to approach them, and never heard back at all.
