### ISSUE TITLE
How How to use cron-job.org rest API, To schedule a job to hit an API on an expiration time, and that API endpoints require some data from the body, Is it possible to do this in JavaScript? 

### ISSUE THREAD

**Issue by xts-bit** [pschlan/cron-job.org#214]
How to use cron-job.org rest API, To schedule a job to hit an API on an expiration time, and that API endpoints require some data from the body, Is it possible to do this in JavaScript?

**Comment by xts-bit** [comment]
@pschlan Can you please help me, Patrick?

**Comment by pschlan** [comment]
This is an issue tracker - for general questions or discussions, please use the "Discussions" section. Thanks!
