### ISSUE TITLE
How i can set my own cron schedule expressions?

### ISSUE THREAD

**Issue by ffscz** [pschlan/cron-job.org#225]
Hello, how can I please set my own Cron start interval? 
For example: “At minute 20 past every 2nd hour.” 
20 */2 * * *

In the Custom section, I cannot individually edit the expression at all.

Thank You

**Comment by pschlan** [comment]
In the custom section, you define the schedule by selecting items from the respective fields (Day of month, Day of week, etc). For the schedule you specified:
 - Minutes: Select 20
 - Hours: Select every other item
 - In all other fields, select all items

There's currently no way to enter a cron expression directly, that is tracked in https://github.com/pschlan/cron-job.org/issues/12
