### ISSUE TITLE
Is the privacy policy outdated?

### ISSUE THREAD

**Issue by mgunyho** [pschlan/cron-job.org#226]
Hi, the [privacy policy](https://cron-job.org/en/privacy/) says that "Access statistics are collected and stored by the Google Analytics service." and "cron-job.org uses Google AdSense to show advertisements". However, when I visit the page, my ad blocker reports no Google scripts, and the site seems to be run on donations instead of ads, which I am very glad to see. Is the privacy policy out of date, or are there ads somewhere on the page?

**Comment by pschlan** [comment]
Yes, this part is out of date. Thanks for reporting. I'll fix this ASAP. Will keep this issue open to track this.

**Comment by pschlan** [comment]
This is fixed now. Thanks again!
