### ISSUE TITLE
I can't delete a specific job

### ISSUE THREAD

**Issue by Sulivan1999** [pschlan/cron-job.org#229]
I have a job that was created through the API, and now when I try to delete it, it is not possible through the panel or through the API.

It is always inactive and does not show history of previous runs, nor is it possible to reactivate it. When trying to delete it, I get the impression that it no longer exists, but it still appears in the dashboard and in the 'failed cronjobs' and 'disabled cronjobs' statistics.

![1](https://github.com/pschlan/cron-job.org/assets/58372000/222118c1-6458-4614-b681-033355d96442)

![2](https://github.com/pschlan/cron-job.org/assets/58372000/7765d69c-af34-4a83-a1ba-4b1e11f4585f)

**Comment by pschlan** [comment]
Hi,

can you share the job ID (via email: info@cron-job.org)? Thanks!

**Comment by pschlan** [comment]
Thanks for sharing the job ID. I manually deleted the job.
This shouldn't have happened and I can't explain it right now. (I've never seen this before.)
Should you ever see this again, please let me know.
Thanks!
