### ISSUE TITLE
Run job button (Interface Web)

### ISSUE THREAD

**Issue by renanmedina** [pschlan/cron-job.org#24]
Could you guys add a "Run Job" button on the web interface, to force it to run asap. :)

**Comment by ecrode** [comment]
Unless the code you are running via corn-job does something specific when it detects the corn-job crawler via IP or agent string, you can simply click the url hyperlink to run the job immediately. Output may not be saved, but you can simply keep the tab open or save it manually.

**Comment by renanmedina** [comment]
Ok, sure. thanks for your reply.
