### ISSUE TITLE
unable to build new instance

### ISSUE THREAD

**Issue by karthikindia** [pschlan/cron-job.org#251]
screen shot - https://pix.cobrasoft.org/image/image.vYl

2.337 -- Found OpenSSL: /usr/lib/x86_64-linux-gnu/libcrypto.so (found version "1.1.1")
2.340 -- Configuring done
2.342 CMake Error at chronos/CMakeLists.txt:35 (add_executable):
2.342 Cannot find source file:
2.342
2.342 cctz/src/civil_time_detail.cc
2.342
2.342 Tried extensions .c .C .c++ .cc .cpp .cxx .m .M .mm .h .hh .h++ .hm .hpp
2.342 .hxx .in .txx
2.342
2.342
2.349 CMake Error: CMake can not determine linker language for target: chronos
2.349 CMake Error: Cannot determine link language for target "chronos".
2.351 -- Generating done
2.353 -- Build files have been written to: /src/cron-job.org/build
------
failed to solve: process "/bin/sh -c cmake -DCMAKE_INSTALL_PREFIX=/opt/chronos .. && make -j && make install" did not complete successfully: exit code: 1

kindly advice
i am using VCPU Ampere server from hetzner with ubuntu 24

**Comment by pschlan** [comment]
Did you run "git submodule init && git submodule update" before trying to build?

**Comment by pschlan** [comment]
No feedback, closing. Please re-open in case the hint didn't help / the issue persists.
