### ISSUE TITLE
Appears to be falsely seeing a 500 error

### ISSUE THREAD

**Issue by upekshapriya** [pschlan/cron-job.org#26]
A cron job is getting a text response and it's being seen as a 500 error - you can see the errors in https://cron-job.org/en/members/jobs/details/?jobid=719606 - I guess you can access this?

**Comment by pschlan** [comment]
Hi,

I've checked the URL of your cron job and it is really giving a 500 response. You can reproduce this by downloading the url on a Linux/Unix command line with "curl -i", e.g. "curl -i https://cl...". This gives in case of your URL:

```
# curl -i (URL REMOVED FOR PRIVACY RESONS)
**HTTP/1.1 500 Internal Server Error**
Date: Thu, 23 Nov 2017 17:11:28 GMT
Content-Type: text/html; charset=UTF-8
Transfer-Encoding: chunked
...
```

So it looks like it's a problem with your script or server config.

**Comment by upekshapriya** [comment]
Yes thanks, it does appear to be a problem with the Wordpress plugin concerned.
