### ISSUE TITLE
API for creating cron jobs?

### ISSUE THREAD

**Issue by drishit96** [pschlan/cron-job.org#3]
Is there any API for creating cron jobs? I want to set cron jobs from my server itself as the job execution date will not be fixed.

**Comment by pschlan** [comment]
Unfortunately there's currently no API, but it might make sense to add one in the future. Thanks for the suggestion.

**Comment by DimuDesigns** [comment]
A REST API that allows for the creation of cron jobs would definitely be awesome. Better yet, it would be even more awesome, if devs could register apps that leverage an OAuth2 flow to create cron jobs on a client's behalf.

**Comment by raullarosa** [comment]
Perhaps the api gateway could be for “premium” members. Kind of how AWS charges after a certain amount of calls. I as a developer would appreciate this service.

**Comment by long1eu** [comment]
Any news on this? :D I am willing to pay for this.

**Comment by long1eu** [comment]
@pschlan friendly ping

**Comment by pschlan** [comment]
We’re currently working on this 😊

**Comment by kdeyko** [comment]
Any updates here?

**Comment by coodoo** [comment]
Bump? 😅

**Comment by pschlan** [comment]
Can people interested in this elaborate a bit on the use cases they have in mind? Just to collect some requirements. Do you plan to use this internally or are you looking for a way to create jobs on behalf of another user, e.g. to provide easy job creation from within your application? Any details would be appreciated.

**Comment by kdeyko** [comment]
@pschlan, my personal use case would be to enable/disable cron jobs via API from my home automation system. For example I have a job for an “Alarm clock” that calls me at the specific time via [callmebot](https://www.callmebot.com/). Sometimes I need to toggle it on some conditions. 
Please let me know if you need more details on this use case.
Thanks!

**Comment by DimuDesigns** [comment]
> Do you plan to use this internally or are you looking for a way to create jobs on behalf of another user, e.g. to provide easy job creation from within your application?

Can we get both?

**Comment by pschlan** [comment]
I'm currently working on a first version of a REST-style API. First docs draft can be found here: https://docs.beta.cron-job.org/rest-api.html

I hope the feature to issue API keys can launch soon.

**Comment by pschlan** [comment]
First version just launched. Head to https://console.cron-job.org -> "Settings" to request an API key.

Closing this here. If you have any suggestions for the API, please create a new issue.

**Comment by kdeyko** [comment]
Tested it today, works like a charm!
Thank you for your hard work! 💪 ❤️
