### ISSUE TITLE
Response data too big on cron-job.org

### ISSUE THREAD

**Issue by Virgula0** [pschlan/cron-job.org#32]
I have some important elements to see in the response... but every execution it returns me Response data too big. Can you increase data size of response ? Also because the status is 200 but appears /!\ in executed column so the cronjob deactivated itself after many execution and I have to active it manually again... 
Can you update this and also add a setting for increase timeout?

**Comment by pschlan** [comment]
This is not a bug in the software. If you have questions, please send us an email. Thanks!

**Comment by surendra-mohan** [comment]
Even I am facing the same issue at my end. @pschlan Can you please share the email address that you have referred to in your previous comment?

**Comment by Alexanderh1988** [comment]
Guys I solved this program using the files of cron job as differents cron jobs with small pieces. If you are using PHP you can set a cron job to domain/cronjob1.php, domain/cronjob2.php limiting the database lets say 10 with $sql="SELECT * FROM `table` LIMIT 10"; to cronjob 1 and the rest in cronjo2...i dunno if I am clear. Grüsse  http://hstech.cl
