### ISSUE TITLE
website down?

### ISSUE THREAD

**Issue by abccbaandy** [pschlan/cron-job.org#34]
Failed to connect to MySQL database backend

**Comment by mihakrut** [comment]
I have this error too!

**Comment by DannyKri** [comment]
Yes me too, @pschlan could you please look? :-)

**Comment by pschlan** [comment]
Working on it. Sorry for the inconvenience.

**Comment by DannyKri** [comment]
@pschlan thank you! No problem, i'm very happy with Cron-job.org! :-)

**Comment by pschlan** [comment]
We're back!
