### ISSUE TITLE
Support PATCH requests

### ISSUE THREAD

**Issue by stevennyman** [pschlan/cron-job.org#49]
I would like to see support for PATCH requests please. This will allow me to use cron-job.org to control my Heroku app using the API. Thanks!

**Comment by stevennyman** [comment]
It looks like it is possible to make a `POST` request and then set the `X-Http-Method-Override` header to `PATCH` to make a `PATCH` request.
From: https://devcenter.heroku.com/articles/platform-api-reference#method-override

Native `PATCH` support would still be better, though.

**Comment by pschlan** [comment]
Shouldn’t be a big deal to add support for it. Will look into this.

**Comment by pschlan** [comment]
PATCH is now supported.

**Comment by stevennyman** [comment]
Thanks!
