### ISSUE TITLE
https://cron-job.org/ Weird cannot edit any cron ? 

### ISSUE THREAD

**Issue by navotera** [pschlan/cron-job.org#52]
I try to edit any cronjobs on the cronlist but I always come out with only one cronjob or not the specific cron that I want to edit. 

Please evaluate. Thank

**Comment by ionutale** [comment]
try this one 
https://www.easycron.com/user

**Comment by pschlan** [comment]
Can you please elaborate a bit more? The description is not clear to me. Editing works fine in my tests.

**Comment by navotera** [comment]
I have not tested it again. For a temporary just closing this issue
