### ISSUE TITLE
"Salutation" field is limited and unnecessary

### ISSUE THREAD

**Issue by serin-delaunay** [pschlan/cron-job.org#56]
"salutation" is defined in [struct.sql](https://github.com/pschlan/cron-job.org/blob/master/database/struct.sql#L104) as having only the two possible values "mr" and "ms" and being mandatory. There are multiple problems with this:

* Many people prefer a different title to "Mr." or "Ms.", for instance "Mx.", "Dr.", or "Rev.", or prefer not to use a title.
* Many people are [nonbinary](https://en.wikipedia.org/wiki/Non-binary_gender) and may find both "Mr." and "Ms." unacceptable to refer to them with.
* Some potential users may sign up with competing services rather than one which will address emails to them with the wrong title.
* By forcing people to choose one of these two options, the gender data you implicitly collect will be inaccurate.
* A cronjob service does not need data about its users' genders.

Some of the ways this could be fixed:
* Make the "salutation" field an optional free-input string (this is the best solution).
* Remove the "salutation" field.
* Make the "salutation" field optional.
* Add more options to the "salutation" field (this is the worst solution; people will inevitably find their preferred titles missing).

**Comment by pschlan** [comment]
Thanks. I fully agree. I will remove it as soon as possible.
