### ISSUE TITLE
Specify timeout parameter

### ISSUE THREAD

**Issue by HannibalZA** [pschlan/cron-job.org#59]
Currently there appears to be a default 30s timeout set to requests.

Can we be allowed to specify a timeout variable other than the default for longer running crons.

![image](https://user-images.githubusercontent.com/2007626/85271755-809d7000-b47b-11ea-9c88-b17e22ea1d56.png)

**Comment by LuizJa** [comment]
Yeah, I'm experiencing the same issue. It will be very helpful to be able to set a custom time.

**Comment by pschlan** [comment]
That’s actually a feature to protect our service. If jobs run for hours, they capture resources on our systems all the time and it’s difficult to provide this for free. We do have some concepts which might allow this in the future. Will update here accordingly once I have news.

**Comment by pschlan** [comment]
Some explanation and mitigations can be found here: https://blog.cron-job.org/errors-explained-timeout-f05e16f6c745

We've also added a configurable tineout in the job editor (within the service's upper limits).
