### ISSUE TITLE
Logins and password on cron-job.org reset not working

### ISSUE THREAD

**Issue by jucedupp** [pschlan/cron-job.org#60]
Hi there

When I receive a password via email, it does not work.  Checked for correctness, spaces etc.

Thanks

**Comment by pschlan** [comment]
Did you click the activation link in the email?

**Comment by jucedupp** [comment]
Hi

Oh! I didn't see that.  I would suggest moving the link to the top, so that
people do not miss that the password has to be activated first.

Jacques

**Comment by pschlan** [comment]
New console now contains improved Password Reset procedure.
