### ISSUE TITLE
Invalid datetime display on new console UI

### ISSUE THREAD

**Issue by suraneti** [pschlan/cron-job.org#63]
New console UI

<img width="1440" alt="Screen Shot 2563-08-26 at 14 32 09" src="https://user-images.githubusercontent.com/26770227/91274737-592f9000-e7a9-11ea-9834-50f8a7a93912.png">

Old console UI

<img width="930" alt="Screen Shot 2563-08-26 at 14 34 04" src="https://user-images.githubusercontent.com/26770227/91274785-68164280-e7a9-11ea-9aa4-0defc423ce14.png">

**Comment by pschlan** [comment]
Hi,

we're now using your local system timezone to display the execution dates. Can you describe which screenshot is wrong and what values you would expect?

**Comment by suraneti** [comment]
Hi @pschlan, 

The DateTime value of the new console UI should be display like a second image.

**Comment by pschlan** [comment]
Hi @suraneti,

can you re-check the console and check if it is OK now? If not, please again supply 2 screenshots (old/new). Thanks a lot!

Patrick

**Comment by suraneti** [comment]
Hi @pschlan,

Both UI displays correctly now. 

Old UI

<img width="1440" alt="Screen Shot 2563-08-31 at 12 49 26" src="https://user-images.githubusercontent.com/26770227/91687007-f5caa700-eb88-11ea-994b-92e598a8a345.png">

New UI

<img width="1224" alt="Screen Shot 2563-08-31 at 12 48 17" src="https://user-images.githubusercontent.com/26770227/91687229-71c4ef00-eb89-11ea-9e9c-c096eb532c0e.png">

Cheers.

**Comment by pschlan** [comment]
Thanks a lot! Glad it works now.
