### ISSUE TITLE
Determining how to autologin when data response is too big 

### ISSUE THREAD

**Issue by mickyfitz808** [pschlan/cron-job.org#66]
Long story short, I know next to nothing about any sort of development/programming knowledge, and I'm looking into cron jobs because my school makes me login everyday for attendance. It tells me my response data is too big, and apparently the solution would be to give it a less data filled page. Because this isn't my project, I've considered automating a script that would solely communicate the login credentials with the server (without using too much data) but I have literally no idea how to go about doing that. How would I write a script that does what I want it to achieve (Autologin at a specific time)? Is there a more efficient way to go about this? 
The login site is here: https://schooltool.bcsd.org/schooltool/
Also, I'm sorry if this isn't the appropriate place to ask for this kind of help. I know the whole point of this site is to maintain/improve cronjobs.org, I just thought this would be the best place to ask for this type of assistance

**Comment by pschlan** [comment]
Thanks for your interest in cron-job.org. You're right that this is probably not the right place to ask this. I'd recommend to ask on stackoverflow.com or similar communities.
