### ISSUE TITLE
How to contribute to translations

### ISSUE THREAD

**Issue by LukeSavefrogs** [pschlan/cron-job.org#67]
How can i contribute to the translation of the [Web Console](https://console.cron-job.org/dashboard)? 

I would like to contribute to the Italian translation :smile:

**Comment by pschlan** [comment]
Thanks a lot! We're planning to publish the source code including language files soon, stay tuned!

**Comment by bloodberries** [comment]
Bahasa Indonesia contributor is ready.

**Comment by pschlan** [comment]
The frontend code is now available. You can find the translations here: https://github.com/pschlan/cron-job.org/tree/master/frontend/src/locales
Feel free to contribute!
