### ISSUE TITLE
Adding timestamp to the request

### ISSUE THREAD

**Issue by veloxls200** [pschlan/cron-job.org#79]
My API request needs the current timestamp to be sent to the server as well. Is there a way to get the Unix timestamp and send it inside the body of the request?

thanks
Aviharsh

**Comment by pschlan** [comment]
Not yet, but having some variables which can be used in the request body or headers might be a nice feature. Any ideas for other useful variables, while we're at it?

**Comment by pschlan** [comment]
Suggested variables:
- Timestamp
- Random string of different sizes
- UDID
