### ISSUE TITLE
Dose it really visit website?

### ISSUE THREAD

**Issue by TyTTT-T** [pschlan/cron-job.org#80]
I have created a conjob and set url to my website.

and set  execution schedule 10 minute.

Then I look conjob history, In column Status, there are Successful 200 OK.

But I go to my database, nothing change.

I have set when somebody visit my website, some data will be add in my database.

Do I miss something?

**Comment by bloodberrys** [comment]
You didn't mention what kind of function you are executing. It would be great if you specified more clues.

**Comment by TyTTT-T** [comment]
Visiting website just through the browser, it will call javascript function automatically I set to change firebase data.
Just visit website.
I have tested manually, it did.
But through conjob, it's not work

In Conjob, I only set url and schedule.

I didn't know what is kind of function meaning?

The settings what I do is above.

**Comment by bloodberrys** [comment]
hmm, Did you see any log or response code from the previous/failed cronjob? I thought your page is secured by authentication by firestore, I found the REST API response code firestore in this docs:
![image](https://user-images.githubusercontent.com/36856722/123036191-d900a800-d416-11eb-8ab7-c9c66b477dee.png)

**Comment by pschlan** [comment]
We don’t execute/evaluate any client side code. cron-job.org is a service to trigger server side processes, it does not simulate  a browser session.

**Comment by TyTTT-T** [comment]
Thanks for reply, I was wrong about  the service that cron-job provided.
