### ISSUE TITLE
Body missing in POST calls

### ISSUE THREAD

**Issue by prem911** [pschlan/cron-job.org#81]
Create a cron job with advanced settings.
Enable username and password
Use POST.
Send some body parameters in json format like
```
{ "key": "Value" }
```
In the receiver api code, the body is received as empty. However authentication comes in header.

**Comment by pschlan** [comment]
Cannot reproduce this. Maybe you need to set the Content-Type header to application/json for your framework to actually make use of the post data?

**Comment by pschlan** [comment]
No feedback yet - please re-open the issue in case you want to add feedback later.
