### ISSUE TITLE
Reciving 404 error\

### ISSUE THREAD

**Issue by PeraDev7** [pschlan/cron-job.org#92]
I added this page on cronjob : 
https://hellaslive.org/n.php
It's a simple php script that i need to run every minutes, but i get the [Failed (HTTP error) 404 Not Found] error.
link : 
https://www.hellaslive.org/n.php

What can i do? Thanks

**Comment by pschlan** [comment]
Your server is sending a 404 response code.

```
> GET /n.php HTTP/2
> Host: hellaslive.org
> User-Agent: curl/7.64.1
> Accept: */*
> 
* Connection state changed (MAX_CONCURRENT_STREAMS == 100)!
< HTTP/2 404 
< date: Thu, 23 Sep 2021 18:22:09 GMT
< content-type: text/html; charset=UTF-8
< x-powered-by: PHP/7.4
< expires: Wed, 11 Jan 1984 05:00:00 GMT
< cache-control: no-cache, must-revalidate, max-age=0
< age: 0
< x-cdn-cache: MISS
< x-cdn-request-id: 726441641
< x-cdn-pop: sbg
< 
```

This is a server config issue. You can try to `header('HTTP/1.1 200 OK')` in your PHP script to override it (at the very beginning).
