### ISSUE TITLE
Feature request: Group Cronjobs into folders

### ISSUE THREAD

**Issue by harryfear** [pschlan/cron-job.org#96]
Wow, this would be amazing!

At the moment on [the Cronjobs page](https://console.cron-job.org/jobs), we have a one-level list of Enabled and then Disabled jobs, like such:

> Enabled jobs
> Disabled jobs

Would be great to have grouping capabilities:—

GROUP 1
> Enabled jobs
> Disabled jobs

GROUP 2
> Enabled jobs
> Disabled jobs

This would be amazing to allow organisation!

**Comment by pschlan** [comment]
Hi,

thanks for the suggestion! This looks like a duplicate of #46 - will continue to track this request there.
