### ISSUE TITLE
Headers cookie cut off value when save 

### ISSUE THREAD

**Issue by letrungdo** [pschlan/cron-job.org#97]
Cron job Advanced POST method with header key: cookie and value: Authorization=Bearer%20eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MTAwLCJlbWFpbCI6ImRvbHRAcnVuc3lzdGVtLm5ldCIsInJvbGUiOjEwLCJpYXQiOjE2MzU3MzA3MDAsImV4cCI6MTYzNjE2MjcwMH0.FDTiBSk1vKUVYXFUyf0pr3dcIYu6xPTzM_zVH_7zI3sfBW3qytbzWqPlsdQha2jTjfdKEcURKTIZqtJH3OpRqUMRzB27dIGj66l9rqL-2kpEjlGkS86M3SMTYrmQ355fbapxmQ0auriTq12uipI5lle808TFmjYvicffTu7KBz2pH4acJ-p5CLcVFQ5dV_QOb3Xon5UVwy96O3C3QWMJoZLedf2W7nvHrHUmR5ViADrGes2Q4LI2uxaB9KyZr7Rs8rfCw_gvpGALE2AQG-0CgRS4ZryglyLhTpd5lNjJPNgSk6yWyL_US_UGbC1FjCXTQMLuhQ-zXg0lKi_d0nLUQQ; connect.sid=s%3AtK2Gb1qY4zRmnSshCXvcRVhcGMYObyVH.J9D08AaAuBQS4daQEVFkFD9PXte26utiCYfes8rr%2Fz4

when SAVE job and then edit job => value is Authorization=Bearer%20eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MTAwLCJlbWFpbCI6ImRvbHRAcnVuc3lzdGVtLm5ldCIsInJvbGUiOjEwLCJpYXQiOjE2MzU3MzA3MDAsImV4cCI6MTYzNjE2MjcwMH0.FDTiBSk1vKUVYXFUyf0pr3dcIYu6xPTzM_zVH_7zI3sfBW3qytbzWqPlsdQha2jTjfdKEcURKTIZqtJH3Op

**Comment by pschlan** [comment]
Thanks - this should be fixed now (increased the length limit for the value)
