### ISSUE TITLE
I can't find the way to set for "every 6 hours".

### ISSUE THREAD

**Issue by tomrambo191** [pschlan/cron-job.org#99]
Hi,

I'm just wondering that how can I set crontab to execute my PHP script for every 6 hours.

Thanks in advance.

**Comment by pschlan** [comment]
Hi,

try this:

- Custom schedule
- Days of month: Select all
- Days of week: Select all
- Months: Select all
- Hours: Select 0, 6, 12 and 18
- Minutes: Select a single entry, e.g. 0

**Comment by tomrambo191** [comment]
Ah!! Thank you. I was blind. 😅

**Comment by tomrambo191** [comment]
> Hi,
> 
> try this:
> 
> * Custom schedule
> * Days of month: Select all
> * Days of week: Select all
> * Months: Select all
> * Hours: Select 0, 6, 12 and 18
> * Minutes: Select a single entry, e.g. 0

Ah!! Thank you. I was blind. 😅
